# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('referencia', models.CharField(db_column='referencia', max_length=50)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'banco',
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('clave', models.CharField(db_column='clave', max_length=3, unique=True)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=500)),
                ('salarios_minimos', models.DecimalField(db_column='salarios_minimos', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'concepto',
            },
        ),
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_column='nombre_completo', max_length=255)),
                ('rfc', models.CharField(db_column='rfc', max_length=13, null=True)),
                ('curp', models.CharField(db_column='curp', max_length=18, null=True)),
                ('entidad_federativa', models.CharField(db_column='entidad_federativa', max_length=50, null=True)),
                ('municipio', models.CharField(db_column='municipio', max_length=80, null=True)),
                ('localidad', models.CharField(db_column='localidad', max_length=100, null=True)),
                ('codigo_postal', models.CharField(db_column='codigo_postal', max_length=5, null=True)),
                ('colonia', models.CharField(db_column='colonia', max_length=255, null=True)),
                ('calle', models.CharField(db_column='calle', max_length=255, null=True)),
                ('numero', models.CharField(db_column='numero', max_length=8, null=True)),
            ],
            options={
                'db_table': 'contribuyente',
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('referencia', models.CharField(db_column='referencia', max_length=20)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=255, null=True)),
                ('banco', models.ForeignKey(db_column='banco', on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='solicitud_pago.Banco')),
            ],
            options={
                'db_table': 'convenio',
            },
        ),
        migrations.CreateModel(
            name='ConvenioPagoConcepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.ForeignKey(db_column='concepto', on_delete=django.db.models.deletion.CASCADE, to='solicitud_pago.Concepto')),
                ('convenio', models.ForeignKey(db_column='convenio', on_delete=django.db.models.deletion.CASCADE, to='solicitud_pago.Convenio')),
            ],
            options={
                'db_table': 'convenio_pago_concepto',
            },
        ),
        migrations.CreateModel(
            name='ReferenciaPago',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('referencia', models.CharField(db_column='referencia', max_length=22, null=True, unique=True)),
                ('vigencia', models.DateField(db_column='vigencia')),
                ('fecha_generacion', models.DateField(db_column='fecha_generacion')),
            ],
            options={
                'db_table': 'referencia_pago',
            },
        ),
        migrations.CreateModel(
            name='SalarioMinimo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(db_column='activo')),
                ('fecha_alta', models.DateField(db_column='fecha_alta')),
                ('fecha_baja', models.DateField(db_column='fecha_baja', null=True)),
            ],
            options={
                'db_table': 'salario_minimo',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPago',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('fecha_solicitud', models.DateField(db_column='fecha_solicitud')),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=8)),
                ('descuento', models.DecimalField(db_column='descuento', decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(db_column='total', decimal_places=2, max_digits=8)),
                ('concepto', models.ForeignKey(db_column='concepto', on_delete=django.db.models.deletion.CASCADE, to='solicitud_pago.Concepto')),
                ('contribuyente', models.ForeignKey(db_column='contribuyente', on_delete=django.db.models.deletion.CASCADE, to='solicitud_pago.Contribuyente')),
                ('deposito', models.ForeignKey(db_column='deposito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pago.Deposito', unique=True)),
                ('referencia_pago', models.ForeignKey(db_column='referencia_pago', on_delete=django.db.models.deletion.CASCADE, to='solicitud_pago.ReferenciaPago')),
                ('salario_minimo', models.ForeignKey(db_column='salario_minimo', on_delete=django.db.models.deletion.CASCADE, to='solicitud_pago.SalarioMinimo')),
            ],
            options={
                'db_table': 'solicitud_pago',
            },
        ),
        migrations.AddField(
            model_name='concepto',
            name='convenios',
            field=models.ManyToManyField(through='solicitud_pago.ConvenioPagoConcepto', to='solicitud_pago.Convenio'),
        ),
    ]
