# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_pago', '0002_auto_20170223_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpago',
            name='deposito',
            field=models.ForeignKey(db_column='deposito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitud_de_pago_related', to='pago.Deposito', unique=True),
        ),
    ]
