# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_pago', '0003_auto_20170307_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpago',
            name='deposito',
            field=models.OneToOneField(db_column='deposito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitud_de_pago_related', to='pago.Deposito'),
        ),
    ]
