# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fecha')),
                ('referencia', models.CharField(db_column='referencia', max_length=255)),
                ('abono', models.DecimalField(db_column='abono', decimal_places=2, max_digits=8)),
                ('saldo', models.DecimalField(db_column='saldo', decimal_places=2, max_digits=8)),
                ('cargo', models.DecimalField(db_column='cargo', decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'deposito',
            },
        ),
        migrations.CreateModel(
            name='ReporteDeposito',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('depositos_reportados', models.IntegerField(db_column='depositos_reportados')),
                ('depositos_procesados', models.IntegerField(db_column='depositos_procesados')),
                ('nombre_original', models.CharField(db_column='nombre_reporte', max_length=255)),
                ('fecha_carga', models.DateField(db_column='fecha_carga')),
                ('ip_cliente', models.CharField(db_column='ip_cliente', max_length=15)),
                ('hash_contenido', models.CharField(db_column='hash_contenido', db_index=True, max_length=40)),
                ('contenido_original', models.TextField(db_column='contenido_original')),
                ('contenido_fallido', models.TextField(db_column='contenido_fallido', null=True)),
            ],
            options={
                'db_table': 'reporte_deposito',
            },
        ),
    ]
