# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pago', '0001_initial'),
        ('solicitud_pago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedeposito',
            name='banco',
            field=models.ForeignKey(db_column='banco', on_delete=django.db.models.deletion.CASCADE, to='solicitud_pago.Banco'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='reporte_deposito',
            field=models.ForeignKey(db_column='reporte_deposito', on_delete=django.db.models.deletion.CASCADE, to='pago.ReporteDeposito'),
        ),
    ]
