# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_auto_20161024_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='multiples_pagos',
            field=models.IntegerField(db_column='multiples_pagos', null=True),
        ),
    ]
