# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0003_deposito_multiples_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='multiples_pagos',
            field=models.IntegerField(db_column='multiples_pagos', default=1),
        ),
    ]
