# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0004_auto_20170303_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='reporte_deposito',
            field=models.ForeignKey(db_column='reporte_deposito', null=True, on_delete=django.db.models.deletion.CASCADE, to='pago.ReporteDeposito'),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='saldo',
            field=models.DecimalField(db_column='saldo', decimal_places=2, max_digits=8, null=True),
        ),
    ]
