# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0005_auto_20170304_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposito',
            name='multiples_pagos',
        ),
    ]
